# Copyright 2017 ECS Team, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
name: ecsteam-influxdb
icon_file: resources/icon.png
label: InfluxDB
description: Deploys an InfluxDB and a Firehose Nozzle to send metrics to it
metadata_version: 1.8                 # Optional, defaults to 1.5

packages:
- name: routing
  type: bosh-release
  path: https://bosh.io/d/github.com/cloudfoundry-incubator/cf-routing-release?v=0.143.0
- name: loggregator
  type: bosh-release
  path: https://bosh.io/d/github.com/cloudfoundry/loggregator?v=65
- name: influxdb
  type: bosh-release
  path: https://bosh.io/d/github.com/vito/influxdb-boshrelease?v=4
  jobs:
  - name: InfluxDB
    templates:
    - name: metron_agent
      release: loggregator
    - name: route_registrar
      release: routing
    - name: influxdb
      release: influxdb
    memory: 32768
    ephemeral_disk: 4096
    persistent_disk: 102400
    cpu: 8
    static_ip: 0
    dynamic_ip: 1
    single_az_only: true
    singleton: true
    properties:
      influxdb:
        database: (( .properties.influxdb_nozzle_db_name.value ))
        replication: "1"
        retention: (( .properties.retention.value ))
        user: (( .properties.influxdb_nozzle_db_user.value ))
        password: (( .properties.influxdb_nozzle_db_password.value ))
      nats:
        machines: (( ..cf.nats.ips ))
        port: 4222
        user: (( ..cf.nats.credentials.identity ))
        password: (( ..cf.nats.credentials.password ))
      route_registrar:
        routes:
        - name: influxdb-admin
          port: 8083
          registration_interval: 20s
          uris:
          - influxdb-admin.(( ..cf.cloud_controller.system_domain.value ))
        - name: influxdb
          port: 8086
          registration_interval: 20s
          uris:
          - influxdb.(( ..cf.cloud_controller.system_domain.value ))
      loggregator_endpoint:
        shared_secret: (( ..cf.doppler.shared_secret_credentials.password ))
      metron_endpoint:
        shared_secret: (( ..cf.doppler.shared_secret_credentials.password ))
      metron_agent:
        deployment: influxdb
        etcd:
          client_cert: "(( .properties.metrics_tls_disabled.value ? .properties.null_string.value : ..cf.properties.cf_etcd_client_cert.cert_pem ))"
          client_key: "(( .properties.metrics_tls_disabled.value ? .properties.null_string.value : ..cf.properties.cf_etcd_client_cert.private_key_pem ))"
      loggregator:
        etcd:
          require_ssl: "(( .properties.metrics_tls_disabled.value ? .properties.false_boolean.value : .properties.true_boolean.value ))"
          machines: "(( .properties.metrics_tls_disabled.value ? ..cf.etcd_server.ips : .properties.etcd_machines.parsed_strings ))"
          ca_cert: (( $ops_manager.ca_certificate ))
- name: influxdb-nozzle-bosh-release
  type: bosh-release
  path: resources/influxdb-nozzle-bosh-release.tgz
  jobs:
  - name: deploy_nozzle
    templates:
    - name: deploy_nozzle
      release: influxdb-nozzle-bosh-release
    lifecycle: errand
    post_deploy: true
    label: Deploy Nozzle
    memory: 2048
    ephemeral_disk: 4096
    cpu: 1
    static_ip: 0
    dynamic_ip: 1
    properties:
      influxdb:
        nozzle:
          admin_client_id: (( ..cf.uaa.admin_client_credentials.identity ))
          admin_client_secret: (( ..cf.uaa.admin_client_credentials.password ))
          db_name: (( .properties.influxdb_nozzle_db_name.value ))
          db_user: (( .properties.influxdb_nozzle_db_user.value ))
          db_password: (( .properties.influxdb_nozzle_db_password.value ))
          subscription_id: (( .properties.influxdb_nozzle_subscription_id.value ))
          client_id: (( .properties.influxdb_nozzle_client_id.value ))
          client_secret: (( .properties.influxdb_nozzle_client_secret.value ))
          foundation: (( .properties.influxdb_nozzle_foundation.value ))
          batch_size: (( .properties.influxdb_nozzle_batch_size.value ))
          tag_fields: (( .properties.influxdb_nozzle_tag_fields.value ))
      buildpack: (( .properties.buildpack.value ))
      instances: (( .properties.instances.value ))
      security:
        user: (( .properties.app_credentials.identity ))
        password: (( .properties.app_credentials.password ))
      ssl:
        skip_cert_verify: (( ..cf.ha_proxy.skip_cert_verify.value ))
      cf:
        admin_user: (( ..cf.uaa.system_services_credentials.identity ))
        admin_password: (( ..cf.uaa.system_services_credentials.password ))
      domain: (( ..cf.cloud_controller.system_domain.value ))
      app_domains:
      - (( ..cf.cloud_controller.apps_domain.value ))
      org: (( .properties.org.value ))
      space: (( .properties.space.value ))
  - name: delete_nozzle
    templates:
    - name: delete_nozzle
      release: influxdb-nozzle-bosh-release
    lifecycle: errand
    pre_delete: true
    label: Delete Nozzle
    memory: 2048
    ephemeral_disk: 4096
    cpu: 1
    static_ip: 0
    dynamic_ip: 1
    properties:
      security:
        user: (( .properties.app_credentials.identity ))
        password: (( .properties.app_credentials.password ))
      ssl:
        skip_cert_verify: (( ..cf.ha_proxy.skip_cert_verify.value ))
      cf:
        admin_user: (( ..cf.uaa.system_services_credentials.identity ))
        admin_password: (( ..cf.uaa.system_services_credentials.password ))
      domain: (( ..cf.cloud_controller.system_domain.value ))
      app_domains:
      - (( ..cf.cloud_controller.apps_domain.value ))
      org: (( .properties.org.value ))
      space: (( .properties.space.value ))

properties:
- name: null_string
  type: string
  default:
- name: etcd_machines
  type: string_list
  default: cf-etcd.service.cf.internal
- name: true_boolean
  type: boolean
  default: true
- name: false_boolean
  type: boolean
  default: false
- name: app_credentials
  type: salted_credentials

forms:
- name: database-properties
  label: Database Config
  properties:
  - name: influxdb_nozzle_db_name
    type: string
    default: cf_metrics
    label: Nozzle destination DB name
    description: The name of the Influx DB to which the nozzle will write its metrics
  - name: influxdb_nozzle_db_user
    type: string
    label: Influx DB User
  - name: influxdb_nozzle_db_password
    type: secret
    label: Influx DB Password
  - name: retention
    type: string
    label: Data Retention Time Span
    default: "14d"
- name: nozzle-config
  label: Nozzle Config
  properties:
  - name: influxdb_nozzle_subscription_id
    type: string
    default: "influxdb-nozzle"
    label: Firehose Subscription ID
    description: ID the Firehose uses to load balance messages between instances. Should be unique from other nozzles
  - name: influxdb_nozzle_client_id
    type: string
    label: Firehose Client ID
    description: A UAA client with `doppler.firehose` scope used to connect to the Firehose
  - name: influxdb_nozzle_client_secret
    type: secret
    label: Firehose Client Secret
  - name: buildpack
    label: Buildpack
    description: The name or URL of the Java Buildpack with which the InfluxDB nozzle will be deployed.
    type: string
  - name: instances
    label: Number of Nozzle instances
    type: integer
    default: 3
    constraints:
      min: 1
  - name: influxdb_nozzle_foundation
    optional: true
    type: string
    label: Foundation Tag
    description: (Optional) If set, all measurements sent to InfluxDB will have a `foundation` tag with this value
  - name: influxdb_nozzle_batch_size
    type: integer
    label: Batch Size
    default: 250
    description: A higher number will reduce load on the InfluxDB server but will increase latency in receiving logs and will increase memory usage in the nozzle.
    constraints:
      min: 1
      max: 500
  - name: influxdb_nozzle_tag_fields
    type: multi_select_options
    label: Fields to Tag
    description: Selected Firehose event fields will be saved as InfluxDB tags
    default: ['job','index','ip','unit','deployment']
    options:
    - name: job
      label: Job
      description: ''
    - name: index
      label: Index
      description: ''
    - name: ip
      label: IP Address
      description: ''
    - name: deployment
      label: Source Deployment
      description: Save the job's BOSH deployment (tile) as an InfluxDB tag
    - name: tags
      label: Custom Tags
    - name: unit
      label: Unit (Valid for ValueMetrics only)
- name: metrics
  label: Metrics
  properties:
  - name: metrics_tls_disabled
    label: Use non-secure communication for metrics
    description: Uncheck this on PCF1.10 or later
    type: boolean
    default: true
